import turtle as t

t.bgcolor('light blue')     # color of the background

def plate():                 
    x=input('Enter the color for the plate:')     # color of the plate (generally it should be white)
    t.goto(-100,0)
    t.begin_fill()
    t.fd(300)
    t.rt(90)
    t.fd(20)
    t.rt(90)
    t.fd(300)
    t.rt(90)
    t.fd(20)
    t.fillcolor(x)
    t.end_fill()
    input('Enter to continue please..')


def layer_1():
    x=input('Enter the color of the 1st layer:')   # color of the 1st layer of the cake
    t.rt(90)
    t.fd(55)
    t.lt(90)
    t.begin_fill()
    t.fd(50)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(50)
    t.fillcolor(x)
    t.end_fill()
    input('Enter to continue please..')

def layer_2():
    x=input('Enter the color of the 2nd layer:')  # color of the 2nd layer of the cake
    t.rt(180)
    t.fd(50)
    t.begin_fill()
    t.fd(20)
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(20)
    t.fillcolor(x)
    t.end_fill()
    input('Enter to continue please...')

def layer_3():
    x=input('Enter the color of the 3rd laer:')  # color of the 3rd layer of the cake 
    t.rt(180)
    t.fd(20)
    t.begin_fill()
    t.fd(10)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(10)
    t.fillcolor(x)
    t.end_fill()
    input('Enter to continue please...')

def layer_4():
    x=input('Enter the color of the 4th layer:')  # color of the 4th layer of the cake
    t.rt(180)
    t.fd(10)
    t.begin_fill()
    t.fd(55)
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(55)
    t.fillcolor(x)
    t.end_fill()
    input('Enter to continue please..')

def frosting():                                  # color of the frosting
    x=input('Enter the color of the frosting:')
    t.rt(180)
    t.fd(55)
    t.rt(180)
    t.begin_fill()
    t.circle(20,180)
    t.fillcolor(x)
    t.end_fill()
    t.rt(180)
    t.begin_fill()
    t.circle(20,180)
    t.fillcolor(x)
    t.end_fill()
    t.rt(180)
    t.begin_fill()
    t.circle(20,180)
    t.fillcolor(x)
    t.end_fill()
    t.rt(180)
    t.begin_fill()
    t.circle(20,180)
    t.fillcolor(x)
    t.end_fill()
    t.rt(180)
    t.begin_fill()
    t.circle(20,180)
    t.fillcolor(x)
    t.end_fill()
    input('Enter to continue please....')


def candle():                            # code for the candle
    t.lt(90)
    t.fd(100)
    t.rt(90)
    t.begin_fill()
    t.fd(30)
    t.lt(90)
    t.fd(10)
    t.lt(90)
    t.fd(30)
    t.fillcolor('red')
    t.end_fill()
    t.rt(180)
    t.begin_fill()
    t.fd(20)
    t.rt(90)
    t.fd(10)
    t.rt(90)
    t.fd(20)
    t.fillcolor('brown')
    t.end_fill()
    t.rt(90)
    t.fd(100)
    input('Enter to continue please..')

def table():                      # code for the table
    t.penup()
    t.goto(-100,-16)
    t.pendown()
    t.begin_fill()
    t.fd(200)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(660)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(250)
    t.fillcolor('brown')
    t.end_fill()
    t.penup()
    t.goto(-250,-110)
    t.lt(90)
    t.begin_fill()
    t.fd(100)
    t.lt(90)
    t.fd(30)
    t.lt(90)
    t.fd(100)
    t.fillcolor('brown')
    t.end_fill()
    t.rt(90)
    t.fd(490)
    t.rt(90)
    t.begin_fill()
    t.fd(100)
    t.lt(90)
    t.fd(30)
    t.lt(90)
    t.fd(100)
    t.fillcolor('brown')
    t.end_fill()
    t.lt(90)
    t.fd(450)
    t.lt(90)
    t.begin_fill()
    t.fd(100)
    t.lt(90)
    t.fd(30)
    t.lt(90)
    t.fd(100)
    t.fillcolor('brown')
    t.end_fill()
    t.rt(90)
    t.fd(290)
    t.rt(90)
    t.begin_fill()
    t.fd(100)
    t.lt(90)
    t.fd(30)
    t.lt(90)
    t.fd(100)
    t.fillcolor('brown')
    t.end_fill()
    input('Press ENTER to exit the program...')



def main():                          # main fucntion 
    plate()
    layer_1()
    layer_2()
    layer_3()
    layer_4()
    frosting()
    candle()
    table()

main() 


